version: '3.8'

services:
  client-frontend:
    image: client:0.0.1
    build: ./Frontend
    restart: always
    ports:
      - '3000:3000'

  client-backend:
    image: server:0.0.1
    build: ./Backend
    restart: always
    ports:
      - "8000:8000"
